name: github-action-release-apk
description: This is an action to release your apk to github release
author: gogoadl
branding:
  icon: 'thumbs-up'
  color: 'white'

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash          
    - run: goodbye.sh
      shell: bash 