name: github-action-release-apk
description: This is an action to release your apk to github release
author: gogoadl
branding:
  icon: 'thumbs-up'
  color: 'white'

inputs:
  asset-name:
    description: 'file name display on releases'
    required: false
    default: "app.apk"
  debug:  # id of input
    description: 'release debug build'
    required: false
    default: 'true'
  base64-keystore:
    description: 'decoded keystore file'
    required: false
    default: 'true'
  key-file:
    description: 'key file for signing apk'
    required: false
    default: 'true'
  keystore-password:
    description: 'Keytstore password for signing apk'
    required: false
    default: 'true'
  keystore-alias:
    description: 'Keystore alias for signing apk'
    required: false
    default: 'true'
  key-password:
    description: 'key password for signing apk'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash

      if: ${{ inputs.debug == true }}
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      shell: bash
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/debug/*.apk
        
      if: ${{ inputs.debug == false }}
    - name: Build Release APK
      run: ./gradlew assembleRelease
      shell: bash
    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/release/*.apk
        
