name: github-action-release-apk
description: This is an action to release your apk to github release
author: gogoadl
branding:
  icon: 'thumbs-up'
  color: 'white'

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      shell: bash
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/debug/*.apk