name: Android CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: github-action-release-apk
      uses: ./.github/workflows/test.yml
      with:
        who-to-greet: test
       # 값을 잘 가져오는지 확인할게요.
    - name: Echo variables
      run: |
          echo lang: "${{ steps.extract.outputs.random-number }}"