name: Android CI

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3 # Necessary to access local action
      # - name: github-action-release-apk
      #   uses: gogoadl/github-action-release-apk@v1.0.0-alpha02

      - uses: actions/checkout@v3 # Necessary to access local action
      - name: github-action-release-apk
        uses: ./.github/actions
        with:
          asset-name: "test.apk"