name: Android CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: github-action-release-apk
      uses: gogoadl/github-action-release-apk@v1.0.0-alpha
